/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dd38d815-774a-42d9-a5c3-26a52fc415bb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZqgaemSm6",
    "aws_user_pools_web_client_id": "5mucq7u6v7535mk00rqtsvmfvm",
    "oauth": {},
    "aws_user_files_s3_bucket": "fit5225image141619-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api5225",
            "endpoint": "https://5pn5mtwicl.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
